"""Codegen: regenerate backend registries and frontend contract constants.

Outputs are committed to the repository and must never be edited by hand.
CI runs this tool and fails on drift. Generated files can be deleted and
rebuilt entirely from contracts/.
"""

from __future__ import annotations

import json
from pathlib import Path

from app.contracts.loader import load_contracts
from app.contracts.validation import validate_contracts
from app.domain.contracts import ContractSet

REPO_ROOT = Path(__file__).resolve().parents[3]
BACKEND_GENERATED = REPO_ROOT / "backend" / "app" / "generated"
FRONTEND_GENERATED = REPO_ROOT / "frontend" / "src" / "api" / "generated"

GENERATED_HEADER = "# GENERATED by app.tools.codegen from contracts/ - DO NOT EDIT.\n"


def _py_literal(value: object) -> str:
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=True)
    if isinstance(value, bool):
        return "True" if value else "False"
    if value is None:
        return "None"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, dict):
        items = ", ".join(f"{_py_literal(k)}: {_py_literal(v)}" for k, v in value.items())
        return "{" + items + "}"
    if isinstance(value, (list, tuple)):
        items = ", ".join(_py_literal(item) for item in value)
        return "(" + items + ("," if len(value) == 1 else "") + ")"
    msg = f"unsupported literal type: {type(value)}"
    raise TypeError(msg)


def _emit_metrics(contracts: ContractSet) -> str:
    lines = [
        GENERATED_HEADER,
        '"""Metric definitions and enum sets (contracts/metrics.json)."""',
        "",
        "from app.domain.contracts import MetricDefinition",
        "",
        "ENUM_SETS: dict[str, tuple[str, ...]] = {",
    ]
    for name in sorted(contracts.enum_sets):
        lines.append(f"    {name!r}: {_py_literal(contracts.enum_sets[name])},")
    lines += ["}", "", "METRIC_DEFINITIONS: dict[str, MetricDefinition] = {"]
    for key in sorted(contracts.metric_definitions):
        metric = contracts.metric_definitions[key]
        lines.append(
            f"    {key!r}: MetricDefinition("
            f"key={metric.key!r}, value_type={metric.value_type!r}, enum_set={metric.enum_set!r}, "
            f"unit={metric.unit!r}, scope={metric.scope!r}, series={metric.series!r}, "
            f"alert_policy={metric.alert_policy!r}, range={_py_literal(metric.range)}),"
        )
    lines.append("}")
    return "\n".join(lines) + "\n"


def _emit_events(contracts: ContractSet) -> str:
    lines = [
        GENERATED_HEADER,
        '"""Event definitions (contracts/events.json)."""',
        "",
        "from app.domain.contracts import EventDefinition",
        "",
        "EVENT_DEFINITIONS: dict[str, EventDefinition] = {",
    ]
    for key in sorted(contracts.event_definitions):
        event = contracts.event_definitions[key]
        lines.append(
            f"    {key!r}: EventDefinition(key={event.key!r}, scope={event.scope!r}, "
            f"sources={_py_literal(event.sources)}, required_fields={_py_literal(event.required_fields)}),"
        )
    lines.append("}")
    return "\n".join(lines) + "\n"


def _emit_operations(contracts: ContractSet) -> str:
    lines = [
        GENERATED_HEADER,
        '"""Operation profiles (contracts/operations.json)."""',
        "",
        "from app.domain.contracts import OperationParameterSchema, OperationProfile, OperationVerification",
        "",
        "OPERATION_PROFILES: dict[str, OperationProfile] = {",
    ]
    for profile_id in sorted(contracts.operation_profiles):
        profile = contracts.operation_profiles[profile_id]
        verification = profile.verification
        lines.append(
            f"    {profile_id!r}: OperationProfile("
            f"id={profile.id!r}, requirement_id={profile.requirement_id!r}, device_type={profile.device_type!r}, "
            f"key={profile.key!r}, channel={profile.channel!r}, risk={profile.risk!r}, "
            f"side_effect={_py_literal(profile.side_effect)}, "
            f"parameter_schema=OperationParameterSchema(raw={_py_literal(profile.parameter_schema.raw)}), "  # noqa: E501
            f"conflict_scope={profile.conflict_scope!r}, "
            f"timeout_seconds={profile.timeout_seconds}, expected_disconnect={_py_literal(profile.expected_disconnect)}, "  # noqa: E501
            f"cancel_policy={profile.cancel_policy!r}, preconditions={_py_literal(profile.preconditions)}, "
            f"verification=OperationVerification(strategy={verification.strategy!r}, success={verification.success!r}, "
            f"ambiguous={verification.ambiguous!r}, prohibition={verification.prohibition!r})),"
        )
    lines.append("}")
    return "\n".join(lines) + "\n"


def _emit_alerts(contracts: ContractSet) -> str:
    lines = [
        GENERATED_HEADER,
        '"""Built-in current-problem rules and value maps (contracts/alert-rules.json)."""',
        "",
        "from app.domain.contracts import AlertRule, BooleanValueMap, EnumValueMap",
        "",
        "ALERT_RULES: tuple[AlertRule, ...] = (",
    ]
    for rule in contracts.alert_rules:
        lines.append(
            f"    AlertRule(rule_key={rule.rule_key!r}, source={rule.source!r}, selector={rule.selector!r}, "
            f"severity={rule.severity!r}, severity_from_value={_py_literal(rule.severity_from_value)}, "
            f"open_after={rule.open_after}, resolve_after={rule.resolve_after}, dedupe={rule.dedupe!r}, "
            f"metric_key={rule.metric_key!r}),"
        )
    lines += [")", "", "ENUM_VALUE_MAPS: tuple[EnumValueMap, ...] = ("]
    for item in contracts.enum_value_maps:
        lines.append(
            f"    EnumValueMap(alert_policy={item.alert_policy!r}, enum_set={item.enum_set!r}, "
            f"values={_py_literal(item.values)}),"
        )
    lines += [")", "", "BOOLEAN_VALUE_MAPS: tuple[BooleanValueMap, ...] = ("]
    for boolean_map in contracts.boolean_value_maps:
        lines.append(
            f"    BooleanValueMap(alert_policy={boolean_map.alert_policy!r}, "
            f"true_outcome={boolean_map.true_outcome!r}, false_outcome={boolean_map.false_outcome!r}),"
        )
    lines.append(")")
    return "\n".join(lines) + "\n"


def _emit_errors(contracts: ContractSet) -> str:
    lines = [
        GENERATED_HEADER,
        '"""Stable error codes (contracts/error-codes.json)."""',
        "",
        "from app.domain.contracts import StableError",
        "",
        "STABLE_ERRORS: dict[str, StableError] = {",
    ]
    for code in sorted(contracts.stable_errors):
        error = contracts.stable_errors[code]
        lines.append(
            f"    {code!r}: StableError(code={error.code!r}, http_status={error.http_status}, "
            f"retry_class={error.retry_class!r}, safe_detail_fields={_py_literal(error.safe_detail_fields)}),"
        )
    lines.append("}")
    return "\n".join(lines) + "\n"


def _emit_capabilities(contracts: ContractSet) -> str:
    lines = [
        GENERATED_HEADER,
        '"""Source requirements and capability whitelist (contracts/capabilities.json)."""',
        "",
        "from app.domain.contracts import Requirement",
        "",
        "REQUIREMENTS: dict[str, Requirement] = {",
    ]
    for req_id in sorted(contracts.requirements):
        requirement = contracts.requirements[req_id]
        lines.append(
            f"    {req_id!r}: Requirement(id={requirement.id!r}, device_type={requirement.device_type!r}, "
            f"kind={requirement.kind!r}, title={requirement.title!r}, metrics={_py_literal(requirement.metrics)}, "
            f"events={_py_literal(requirement.events)}, operations={_py_literal(requirement.operations)}),"
        )
    lines += ["}", "", "REQUIREMENT_BY_CAPABILITY: dict[str, str] = {"]
    for key in sorted(contracts.requirements_by_capability):
        lines.append(f"    {key!r}: {contracts.requirements_by_capability[key].id!r},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _emit_http_api(contracts: ContractSet) -> str:
    lines = [
        GENERATED_HEADER,
        '"""HTTP/SSE/WS endpoint whitelist (contracts/http-api.json)."""',
        "",
        "from app.domain.contracts import HttpEndpoint",
        "",
        "HTTP_ENDPOINTS: dict[str, HttpEndpoint] = {",
    ]
    for operation_id in sorted(contracts.http_endpoints):
        endpoint = contracts.http_endpoints[operation_id]
        lines.append(
            f"    {operation_id!r}: HttpEndpoint(method={endpoint.method!r}, path={endpoint.path!r}, "
            f"operation_id={endpoint.operation_id!r}, support_id={endpoint.support_id!r}),"
        )
    lines.append("}")
    return "\n".join(lines) + "\n"


def _emit_hardware_targets(contracts: ContractSet) -> str:
    lines = [
        GENERATED_HEADER,
        '"""Hardware certification targets (contracts/hardware-targets.json)."""',
        "",
        "from app.domain.contracts import HardwareTarget",
        "",
        "HARDWARE_TARGETS: dict[str, HardwareTarget] = {",
    ]
    for target_id in sorted(contracts.hardware_targets):
        target = contracts.hardware_targets[target_id]
        lines.append(
            f"    {target_id!r}: HardwareTarget(target_id={target.target_id!r}, device_type={target.device_type!r}, "
            f"vendor={target.vendor!r}, declared_target={target.declared_target!r}, "
            f"certification_scope={target.certification_scope!r}, adapter_key={target.adapter_key!r}),"
        )
    lines.append("}")
    return "\n".join(lines) + "\n"


def _ts_literal(value: object) -> str:
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=True)
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, dict):
        items = ", ".join(f"{_ts_literal(k)}: {_ts_literal(v)}" for k, v in value.items())
        return "{" + items + "}"
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_ts_literal(item) for item in value) + "]"
    msg = f"unsupported literal type: {type(value)}"
    raise TypeError(msg)


def _emit_frontend(contracts: ContractSet) -> str:
    device_types = sorted({r.device_type for r in contracts.requirements.values()})
    metric_keys = sorted(contracts.metric_definitions)
    event_keys = sorted(contracts.event_definitions)
    capability_keys = sorted(contracts.requirements_by_capability)
    error_codes = sorted(contracts.stable_errors)
    operation_keys = sorted(contracts.operation_profiles)
    enum_sets = contracts.enum_sets
    lines = [
        "// GENERATED by app.tools.codegen from contracts/ - DO NOT EDIT.",
        "// eslint-disable",
        "",
        f"export const PRODUCT_VERSION = {_ts_literal(contracts.product_version)};",
        "",
        "export const DEVICE_TYPES = " + _ts_literal(device_types) + " as const;",
        "export type DeviceType = (typeof DEVICE_TYPES)[number];",
        "",
        "export const METRIC_KEYS = " + _ts_literal(metric_keys) + " as const;",
        "export type MetricKey = (typeof METRIC_KEYS)[number];",
        "",
        "export const EVENT_KEYS = " + _ts_literal(event_keys) + " as const;",
        "export type EventKey = (typeof EVENT_KEYS)[number];",
        "",
        "export const CAPABILITY_KEYS = " + _ts_literal(capability_keys) + " as const;",
        "export type CapabilityKey = (typeof CAPABILITY_KEYS)[number];",
        "",
        "export const OPERATION_PROFILE_IDS = " + _ts_literal(operation_keys) + " as const;",
        "export type OperationProfileId = (typeof OPERATION_PROFILE_IDS)[number];",
        "",
        "export const ERROR_CODES = " + _ts_literal(error_codes) + " as const;",
        "export type ErrorCode = (typeof ERROR_CODES)[number];",
        "",
        "export const METRIC_META: Record<string, { valueType: string; unit: string | null; scope: string; series: string; alertPolicy: string }> = {",  # noqa: E501
    ]
    for key in metric_keys:
        metric = contracts.metric_definitions[key]
        lines.append(
            f"  {key!r}: {{ valueType: {metric.value_type!r}, unit: {_ts_literal(metric.unit)}, "
            f"scope: {metric.scope!r}, series: {metric.series!r}, alertPolicy: {metric.alert_policy!r} }},"
        )
    lines += ["};", "", "export const ENUM_SETS: Record<string, readonly string[]> = {"]
    for name in sorted(enum_sets):
        lines.append(f"  {name!r}: " + _ts_literal(list(enum_sets[name])) + ",")
    lines += ["};", "", "export const REQUIREMENTS: Record<string, { deviceType: DeviceType; kind: 'monitoring' | 'operation'; title: string }> = {"]  # noqa: E501
    for req_id in sorted(contracts.requirements):
        requirement = contracts.requirements[req_id]
        lines.append(
            f"  {req_id!r}: {{ deviceType: {requirement.device_type!r}, kind: {requirement.kind!r}, title: {requirement.title!r} }},",  # noqa: E501
        )
    lines.append("};")
    return "\n".join(lines) + "\n"


def run() -> None:
    contracts = load_contracts()
    validate_contracts(contracts)

    BACKEND_GENERATED.mkdir(parents=True, exist_ok=True)
    FRONTEND_GENERATED.mkdir(parents=True, exist_ok=True)

    emitters: dict[str, str] = {
        "metrics.py": _emit_metrics(contracts),
        "events.py": _emit_events(contracts),
        "operations.py": _emit_operations(contracts),
        "alerts.py": _emit_alerts(contracts),
        "errors.py": _emit_errors(contracts),
        "capabilities.py": _emit_capabilities(contracts),
        "http_api.py": _emit_http_api(contracts),
        "hardware_targets.py": _emit_hardware_targets(contracts),
    }
    for filename, content in emitters.items():
        (BACKEND_GENERATED / filename).write_text(content, encoding="utf-8")

    (FRONTEND_GENERATED / "contracts.ts").write_text(_emit_frontend(contracts), encoding="utf-8")
    print("Codegen complete.")


if __name__ == "__main__":
    run()
